Change NX_ADD_PLUGINS value to string format
Fixes

ERROR: The Compose file './docker-compose.yml' is invalid because: 
services.postiz.environment.NX_ADD_PLUGINS contains false, which is an invalid type, it should be a string, number, or a null